"""initial_migration

Revision ID: 4b29670cd67e
Revises:
Create Date: 2025-11-11 03:00:13.758723

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b29670cd67e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("doc_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.String(length=8), nullable=False),
        sa.Column("health_user_ci", sa.String(length=8), nullable=False),
        sa.Column("clinic_name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("s3_url", sa.String(length=512), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("content_type", sa.String(length=128), nullable=True),
        sa.Column("provider_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("doc_id"),
    )
    op.create_index(
        op.f("ix_documents_clinic_name"), "documents", ["clinic_name"], unique=False
    )
    op.create_index(
        op.f("ix_documents_created_by"), "documents", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_documents_health_user_ci"),
        "documents",
        ["health_user_ci"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_documents_health_user_ci"), table_name="documents")
    op.drop_index(op.f("ix_documents_created_by"), table_name="documents")
    op.drop_index(op.f("ix_documents_clinic_name"), table_name="documents")
    op.drop_table("documents")
    # ### end Alembic commands ###
