"""initial_migration

Revision ID: 4b29670cd67e
Revises: 
Create Date: 2025-11-11 03:00:13.758723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b29670cd67e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_history_access_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('health_user_ci', sa.String(length=8), nullable=False),
    sa.Column('health_worker_ci', sa.String(length=8), nullable=False),
    sa.Column('clinic_name', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('viewed', sa.Boolean(), nullable=False),
    sa.Column('decision_reason', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_history_access_logs_clinic_name'), 'clinical_history_access_logs', ['clinic_name'], unique=False)
    op.create_index(op.f('ix_clinical_history_access_logs_health_user_ci'), 'clinical_history_access_logs', ['health_user_ci'], unique=False)
    op.create_index(op.f('ix_clinical_history_access_logs_health_worker_ci'), 'clinical_history_access_logs', ['health_worker_ci'], unique=False)
    op.create_table('documents',
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.String(length=8), nullable=False),
    sa.Column('health_user_ci', sa.String(length=8), nullable=False),
    sa.Column('clinic_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('s3_url', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_index(op.f('ix_documents_clinic_name'), 'documents', ['clinic_name'], unique=False)
    op.create_index(op.f('ix_documents_created_by'), 'documents', ['created_by'], unique=False)
    op.create_index(op.f('ix_documents_health_user_ci'), 'documents', ['health_user_ci'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_health_user_ci'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_by'), table_name='documents')
    op.drop_index(op.f('ix_documents_clinic_name'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_clinical_history_access_logs_health_worker_ci'), table_name='clinical_history_access_logs')
    op.drop_index(op.f('ix_clinical_history_access_logs_health_user_ci'), table_name='clinical_history_access_logs')
    op.drop_index(op.f('ix_clinical_history_access_logs_clinic_name'), table_name='clinical_history_access_logs')
    op.drop_table('clinical_history_access_logs')
    # ### end Alembic commands ###
